export enum TimeSheetStatus {
  CREATED = 'CREATED',

  SGE_VALIDATION_PENDING = 'SGE_VALIDATION_PENDING',

  EMPLOYER_VALIDATION_PENDING = 'EMPLOYER_VALIDATION_PENDING',

  VALIDATED = 'VALIDATED',

  REJECTED = 'REJECTED',
}
